### ISSUE TITLE
App starts but is not visible

### ISSUE THREAD

**Issue by amritbrar** [flathub/io.github.martinrotter.rssguardlite#41]
Clicking on icon starts the app, but it isn't visible for the user. Rolling back to KDE `5.15-23.08` runtime fixes the problem.

![Screenshot from 2024-04-11 16-30-55](https://github.com/flathub/io.github.martinrotter.rssguardlite/assets/72675494/6e48b517-1260-4f36-8854-94819b02484c)

RssGuardLite Version: 4.6.6
Runtime: org.kde.Platform/x86_64/6.7
Host: Fedora Silverblue (39.20240410.1)

See also: [rssguard commit](https://github.com/martinrotter/rssguard/commit/4ce7b547d720767cd4caed530c7118d1f96325ef)

**Comment by guihkx** [comment]
How weird. I personally use the Lite version too, and it's working just fine for me.

Can you post the app logs?

```
flatpak run io.github.martinrotter.rssguardlite
```

Also, if you are on Wayland, can you please try temporarily forcing XWayland?

```
flatpak run --nosocket=fallback-x11 --socket=x11 io.github.martinrotter.rssguardlite
```

**Comment by amritbrar** [comment]
After running: `flatpak run --nosocket=fallback-x11 --socket=x11 io.github.martinrotter.rssguardlite`

[rssguardlite_log.txt](https://github.com/flathub/io.github.martinrotter.rssguardlite/files/14952179/rssguardlite_log.txt)

Running the above with `-v` as well includes this in the debug log:

`F: /var/home/a/.local/share/flatpak/runtime/org.kde.Platform/x86_64/6.7/25a37c5be7fe5e2fcd7e51f0a24bfcd43195df7cb4f269a4e6b9ebc0fa6652dd/files/lib32 does not exist
`

**Comment by martinrotter** [comment]
Yes, like I said, for some reason 6.7.x Qt is somehow very very buggy for me. Maybe it's me, maybe it's Qt regressions. I was not able to get one solid stacktrace actually showing what is wrong.

I have similar issues and crashes on Windows when testing with Qt 6.7.0 too. Random freezing, crashes when initializing QtWebEngine etc.

Hell, even 6.6 was buggy but seems rather good now.

It just suxx.

**Comment by guihkx** [comment]
I was able to reproduce this on a clean environment, but only on the GNOME Wayland session. 

Steps to reproduce:

1. Log into a GNOME Wayland session
2. Open RSS Guard
3. Maximize the window
4. Restart RSS Guard
5. Main window won't be visible anymore

I couldn't find a way to remedy this, but I noticed that if you un-maximize RSS Guard before quitting, the issue won't be triggered the next launch.

Another dumb workaround to at least make the window show up, is to manually set `window_is_maximized` to `false` in `~/.var/app/io.github.martinrotter.rssguardlite/config/RSS Guard 4/config/config.ini`.

Based on a quick search through Qt bugs, I came across [this bug report](https://bugreports.qt.io/browse/QTBUG-121445), which looks very similar to what we're seeing here.

The problem is, devs seem to be debating whether this is a regression or not... :/

@martinrotter Wild idea here: Do you think that setting a minimum window size for RSS Guard would be dumb? Though I don't even know if such workaround would even fix this. I'm available for testing, however.

**Comment by martinrotter** [comment]
I will have to look because the source code around saving/loading of main window position/size/maximize state is already riddled with problems from the past, the feature was "re-fixed" many times due to not working etc.

I will try to reproduce on Windows and double-check the code responsible for this.

**Comment by guihkx** [comment]
Thank you, but I seriously doubt this will be reproducible on Windows.

Apparently, it's not even reproducible on all Wayland compositors (e.g. KDE's KWin doesn't seem affected).

**Comment by guihkx** [comment]
In the meantime, I suppose I could downgrade to 6.6 to see if it "fixes things".
